kind = "web"
previewPath = "/"
title = "Examverse"
version = "1.0.0"
id = "artifacts/examverse"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23432

[services.development]
run = "pnpm --filter @workspace/examverse run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/examverse", "run", "build" ]
publicDir = "artifacts/examverse/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23432"
BASE_PATH = "/"
